///////////////////////////////////////////////////////////////////////////////
// ChildModule.h
#pragma once

#include "VersionedCppInterfaces.h"

class CChildModule 
	: public ITComObject
	, public ITcADI
	, public ITcWatchSource
///<AutoGeneratedContent id="InheritanceList">
	, public I_ChildIncrement
///</AutoGeneratedContent>
{
public:
	DECLARE_IUNKNOWN()
	DECLARE_IPERSIST_LIB()
	DECLARE_ITCOMOBJECT_LOCKOP()
	DECLARE_ITCADI()
	DECLARE_ITCWATCHSOURCE()
	DECLARE_OBJPARAWATCH_MAP()
	DECLARE_OBJDATAAREA_MAP()

	CChildModule();
	virtual	~CChildModule();

///<AutoGeneratedContent id="InterfaceMembers">
	// I_ChildIncrement
	virtual HRESULT TCOMAPI Increment();

///</AutoGeneratedContent>

protected:
	DECLARE_ITCOMOBJECT_SETSTATE();

///<AutoGeneratedContent id="Members">
	ChildModuleOutputs m_Outputs;
///</AutoGeneratedContent>
};
