///////////////////////////////////////////////////////////////////////////////
// VersionedCppServices.h

#pragma once

#include "TcServices.h"

const ULONG DrvID_VersionedCpp = 0x3F000000;
#define SRVNAME_VERSIONEDCPP "VersionedCpp"

///<AutoGeneratedContent id="ClassIDs">
const CTCID CID_VersionedCppCParentModule = {0xde561753,0xb26b,0x4d44,{0x83,0x99,0x05,0x9c,0x1a,0x92,0x07,0x11}};
const CTCID CID_VersionedCppCChildModule = {0xf3c3b4bb,0x05c8,0x4a95,{0x8c,0x2c,0x77,0x96,0xcf,0x50,0x9e,0x3c}};
///</AutoGeneratedContent>

///<AutoGeneratedContent id="ParameterIDs">
///</AutoGeneratedContent>

///<AutoGeneratedContent id="DataTypes">
typedef struct _ChildModuleOutputs
{
	SHORT nCnt;
} ChildModuleOutputs, *PChildModuleOutputs;

///</AutoGeneratedContent>



///<AutoGeneratedContent id="DataAreaIDs">
#define ADI_ChildModuleOutputs 1
///</AutoGeneratedContent>

///<AutoGeneratedContent id="InterfaceIDs">
#if !defined(_TC_IID_62DBD04A_4A50_42EF_BFE8_75D8163C328A_INCLUDED_)
#define _TC_IID_62DBD04A_4A50_42EF_BFE8_75D8163C328A_INCLUDED_
TCOM_DECL_INTERFACE("62dbd04a-4a50-42ef-bfe8-75d8163c328a", I_ChildIncrement)
#endif // !defined(_TC_IID_62DBD04A_4A50_42EF_BFE8_75D8163C328A_INCLUDED_)

#if !defined(_TC_IID_6E3C37A3_8DBC_4092_A431_0BDB0E779C3E_INCLUDED_)
#define _TC_IID_6E3C37A3_8DBC_4092_A431_0BDB0E779C3E_INCLUDED_
TCOM_DECL_INTERFACE("6e3c37a3-8dbc-4092-a431-0bdb0e779c3e", I_ParentRegister)
#endif // !defined(_TC_IID_6E3C37A3_8DBC_4092_A431_0BDB0E779C3E_INCLUDED_)

///</AutoGeneratedContent>

///<AutoGeneratedContent id="EventClasses">
///</AutoGeneratedContent>
