///////////////////////////////////////////////////////////////////////////////
// VersionedCppClassFactory.cpp
#include "TcPch.h"
#pragma hdrstop

#include "VersionedCppClassFactory.h"
#include "VersionedCppServices.h"
#include "VersionedCppVersion.h"
#include "ParentModule.h"
#include "ChildModule.h"

BEGIN_CLASS_MAP(CVersionedCppClassFactory)
///<AutoGeneratedContent id="ClassMap">
	CLASS_ENTRY_LIB(VID_VersionedCpp, CID_VersionedCppCParentModule, SRVNAME_VERSIONEDCPP "!CParentModule", CParentModule)
	CLASS_ENTRY_LIB(VID_VersionedCpp, CID_VersionedCppCChildModule, SRVNAME_VERSIONEDCPP "!CChildModule", CChildModule)
///</AutoGeneratedContent>
END_CLASS_MAP()

CVersionedCppClassFactory::CVersionedCppClassFactory() : CObjClassFactory()
{
	TcDbgUnitSetImageName(TCDBG_UNIT_IMAGE_NAME_TMX(SRVNAME_VERSIONEDCPP));
#if defined(TCDBG_UNIT_VERSION)
	TcDbgUnitSetVersion(TCDBG_UNIT_VERSION(VersionedCpp));
#endif //defined(TCDBG_UNIT_VERSION)
}

