///////////////////////////////////////////////////////////////////////////////
// VersionedCppInterfaces.h

#pragma once

#include "TcInterfaces.h"
#include "TcIoInterfaces.h"
#include "TcRtInterfaces.h"
#include "VersionedCppServices.h"

///<AutoGeneratedContent id="Interfaces">
#if !defined(_TC_TYPE_62DBD04A_4A50_42EF_BFE8_75D8163C328A_INCLUDED_)
#define _TC_TYPE_62DBD04A_4A50_42EF_BFE8_75D8163C328A_INCLUDED_
struct __declspec(novtable) I_ChildIncrement : public ITcUnknown
{
	virtual HRESULT TCOMAPI Increment()=0;
};
_TCOM_SMARTPTR_TYPEDEF(I_ChildIncrement, IID_I_ChildIncrement);
#endif // !defined(_TC_TYPE_62DBD04A_4A50_42EF_BFE8_75D8163C328A_INCLUDED_)

#if !defined(_TC_TYPE_6E3C37A3_8DBC_4092_A431_0BDB0E779C3E_INCLUDED_)
#define _TC_TYPE_6E3C37A3_8DBC_4092_A431_0BDB0E779C3E_INCLUDED_
struct __declspec(novtable) I_ParentRegister : public ITcUnknown
{
	virtual HRESULT TCOMAPI Register(ITComObject* iPtrChild)=0;
};
_TCOM_SMARTPTR_TYPEDEF(I_ParentRegister, IID_I_ParentRegister);
#endif // !defined(_TC_TYPE_6E3C37A3_8DBC_4092_A431_0BDB0E779C3E_INCLUDED_)

///</AutoGeneratedContent>
